cards/urls.py
from django.urls import path
from . import views

app_name='cards'
urlpatterns = [
    path('', views.SplashView.as_view(), name='splash'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.RegistrationView.as_view(), name='register'),
    path('thankyou', views.RegistrationLandingView.as_view(), name='landing'),
    path('checklogin', views.logged_in, name='checklogin'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('create_card', views.create_card, name='card-create'),
    path('delete_card', views.delete_card, name='card-delete'),
    path('card/<str:id>', views.CardDetailView.as_view(), name='card-detail'),
    path('wallet/<int:id>', views.WalletDetailView.as_view(),name='wallet-detail'),
    # path('wallets'),
]

watermark/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls'))
]

cards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class WatermarkUser(User):

    pass

class UserCard(models.Model):
    id = models.AutoField(db_index=True, primary_key=True)
    owner = models.ForeignKey(WatermarkUser, on_delete=models.SET_NULL, null=True)
    name = models.TextField(max_length=200, default='New Card')
    text = models.TextField(max_length=1000, default='Default text.')
    address_line_1 = models.TextField(max_length=1000, null=True)
    address_line_2 = models.TextField(max_length=1000, null=True)
    city = models.TextField(max_length=200, null=True)
    pass

class Wallet(models.Model):
    user = models.ForeignKey(WatermarkUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='New wallet')
    card = models.ManyToManyField(UserCard)
    pass

class Profile(models.Model):
    user = models.OneToOneField(WatermarkUser, on_delete=models.CASCADE)
    bio = models.TextField(max_length=10000)
    default_card = models.OneToOneField(UserCard, on_delete=models.SET_NULL, null=True)
    first_name = models.TextField(max_length=100, null=True)
    last_name = models.TextField(max_length=100, null=True)
    pass


@receiver(post_save, sender=WatermarkUser)
def user_saved(sender, instance, created, **kwargs):
    if created:
        wallet = Wallet.objects.create(user=instance)
        profile = Profile.objects.create(user=instance)
        profile.bio = "Default text for profile bio."
        print("An instance of WatermarkUser was created.")
    else:
        instance.profile.save()

cards/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.core.validators import validate_email

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='First name', max_length=256)
    last_name = forms.CharField(label='Last name', max_length=256)
    email = forms.CharField(label='Email', max_length=256)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        validate_email(email)        

class LoginForm(AuthenticationForm):
    pass

cards/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views import generic
from django.urls import reverse_lazy
from .forms import RegistrationForm, LoginForm
from .models import WatermarkUser, UserCard, Wallet
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from time import time

import json

class SplashView(TemplateView):
    template_name = "cards/splash.html"

class RegistrationLandingView(TemplateView):
    template_name = "cards/landing.html"

class RegisterView(TemplateView):
    template_name = "cards/register.html"

# def register(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             return HttpResponseRedirect('/')
#     else:
#         form = UserCreationForm()

#     return render(request, 'cards/register.html', {'form' : form})

class ProfileView(generic.TemplateView):
    template_name = "cards/profile.html"

    def get_cards(self):
        user = WatermarkUser.objects.get(username = self.request.user)
        return user.usercard_set.all()

    def default_card(self):
        user = WatermarkUser.objects.get(username=self.request.user)
        return user.profile.default_card.id

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        # context['user']
        return context

    def get_wallets(self):
        user = WatermarkUser.objects.get(username = self.request.user)
        return user.wallet_set.all()

class CardDetailView(generic.TemplateView):
    template_name = "cards/carddetail.html"

    def get_context_data(self, **kwargs):
        context = super(CardDetailView, self).get_context_data(**kwargs)
        context['id'] = self.kwargs.get('id')
        return context

class WalletDetailView(generic.TemplateView):
    template_name = "cards/walletdetail.html"

def get_cards(request):
    if request.user:
        user = WatermarkUser.objects.get(username=request.user)


def create_card(request):
    if request.user:
        user = WatermarkUser.objects.get(username=request.user)
        print("Making a card for ", request.user)
        card = UserCard.objects.create(owner=user)
        if (user.profile.default_card is None):
            user.profile.default_card = card
            user.profile.save()
        data = json.loads(request.body.decode('utf-8'))
        print(data['name'])

    return JsonResponse({'success': True})

def delete_card(request):
    if request.user:
        data = json.loads(request.body.decode('utf-8'))
        user = WatermarkUser.objects.get(username=request.user)
        card = UserCard.objects.get(id=data['id'])
        card.delete()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})

class RegistrationView(FormView):
    template_name = "cards/register.html"
    form_class = RegistrationForm
    success_url = "/thankyou"

    def form_valid(self, form):
        print("Valid form!")
        data = form.cleaned_data
        user = WatermarkUser.objects.create_user(email=data['email'],username=data['username'],password=data['password1'])
        user.profile.first_name = data['first_name']
        user.profile.last_name = data['last_name']
        user.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print("NOT VALID")
        print(form.cleaned_data)
        return super().form_invalid(form)

class LoginView(FormView):
    template_name = "cards/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("cards:profile")

    def form_valid(self, form):
        print("Login submitted")
        print(form.cleaned_data)
        data = form.cleaned_data
        user = authenticate(self.request, username=data['username'], password=data['password'])
        if user is not None:
            login(self.request, user)
            print('Login successful')
        else:
            print('Login unsuccessful')
        return super().form_valid(form)

    def form_invalid(self, form):
        print("failed")
        print(form.cleaned_data)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['time'] = time()
        return context

def logged_in(request):
    if request.user.is_authenticated:
        return HttpResponse("You're logged in as {}".format(request.user.username))
    else:
        return HttpResponse("You're not logged in")

cards/templates/cards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            display: flex;
            justify-content: center;
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        .container {
            align-items: center;
            display: flex;
            flex-direction:column;
            width: 700px;
        }
        
        .shadow {
            box-shadow: 2px 2px 5px 0px rgba(191,191,191,1);
            padding: 15px;
        }

        .logo-container {
            min-height: 200px;
        }

        .errorlist {
            list-style-type: none;
        }

        .login-form tr {
            width: 600px;
        }
    </style>
    {% block style %}
    {% endblock %}
    <title>{% block title %}Watermark{% endblock %}</title>
</head>

<body>
    <div id="content" class="container shadow">
        {% block content %}This page seems to be blank.{% endblock %}
    </div>
</body>
    {% block scripts %}{% endblock %}
</html>

cards/templates/cards/carddetail.html
<body>
    {{ id }}
</body>

cards/templates/cards/landing.html
{% extends 'cards/base.html' %}
{% block content %}

Thank you for signing up!
You will be redirected in 3 seconds.

{% endblock%}
{% block scripts%}
<script>
    function redirect() {
        window.location.href="{% url 'cards:login' %}"
    }
    setTimeout(redirect, 3000)
</script>
{% endblock %}

cards/templates/cards/login.html
{% extends 'cards/base.html' %}

{% block content %}
<div class="logo-container">
    <h1>Watermark Logo</h1>
</div>
<form action="{% url 'cards:login' %}" method="post" class="login-form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
<a href="">Reset password</a>
<a href="{% url 'cards:register' %}">Don't have an account?</a>
{% endblock %}

cards/templates/cards/profile.html
{% extends 'cards/base.html' %} 
{% block style %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'cards/styles/profile.css' %}">
{% endblock %} 
{% block content %}
<h1>Welcome, {{ user }}</h1>
<video id="scan-view">
</video>
<button id="scan-button" onclick="launch_instascan()" disabled>Scan</button>
<button id="stop-button" style="display:none">Stop</button>
{% if view.get_cards %}
<div class="card-container">
    {% for card in view.get_cards %}
    <div class="card shadow">
        <div>{{ card.name }}</div>
        <div id="card-code-{{ card.id }}" class="qr-view">
            <div style="display:none;">{{ card.id }}</div>
        </div>
        <div>
            {{ card.text }}
        </div>
        {% if card.id == view.default_card %}
        <div>This is the default card.</div>
        {% endif %}
        <button onclick="deleteCard('{{ card.id }}')">Delete</button>
    </div>
    {% endfor %}
    <div class="card shadow">
        <button onclick="createCard()">Add Card</button>
    </div>
</div>
{% else %}
<div>No cards found for {{ user }}</div>
<div class="card shadow">
    <button onclick="createCard()">Add Card</button>
</div>
{% endif %}  
<div class="card-container">
    {% for wallet in view.get_wallets %}
    <div class="card shadow">
        {{ wallet.name }}
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block scripts %}

{% load static %}
<script src="{% static 'cards/scripts/cookie.js' %}"></script>
<script src="{% static 'cards/scripts/qrcode.js' %}"></script>
<script src="{% static 'cards/scripts/profile.js' %}"></script>
<script onload="instascan_ready()" src="{% static 'cards/scripts/instascan.min.js' %}"></script> {% endblock %}

cards/templates/cards/register.html
{% extends 'cards/base.html' %}
{% block content %}
<form action="{% url 'cards:register' %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cards/templates/cards/splash.html
{% extends 'cards/base.html' %}
{% block content %}
<p>This is the splash page.</p>
<a href="{% url 'cards:login' %}">This should go to the login page.</a>
{% endblock %}

cards/templates/cards/wallet.html
{% extends 'cards/base.html' %}
{% block content %}
{% endblock %}

cards/templates/cards/walletdetail.html
{% extends 'cards/base.html' %}
{% block content %}
<div>
    {{ id }}
</div>
{% endblock %}